Enable bot to push execution report changes
Added permissions for the bot to push changes and included a step to commit the execution report.

diff --git a/.github/workflows/run-jupyter-notebooks.yml b/.github/workflows/run-jupyter-notebooks.yml
--- a/.github/workflows/run-jupyter-notebooks.yml
+++ b/.github/workflows/run-jupyter-notebooks.yml
@@ -11,6 +11,8 @@ on:
 jobs:
   run-notebooks:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write  # Allows the bot to push the .md file
     steps:
       - name: Checkout Current Repo
         uses: actions/checkout@v4
@@ -76,3 +78,13 @@ jobs:
 
       - name: Post Summary to Workflow
         run: cat report.md >> $GITHUB_STEP_SUMMARY
+
+      - name: Commit Report to Current Repo
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          
+          git add report.md
+          # The '|| exit 0' prevents the workflow from failing if the report hasn't changed
+          git commit -m "docs: update execution report [skip ci]" || exit 0
+          git push
